In [65]:
import numpy as np
from numpy import loadtxt

In [66]:
a = np.loadtxt("C:\Studies\Sem 4\PH206\Labs\Lab4\lab4matrix1.txt", delimiter = ",")
n = len(a)
print(a)

[[ 3.  7. 13.]
 [ 1.  5.  3.]
 [12.  3. -5.]]


In [67]:
for i in range(0, n):
    
    
    s = 0
    for j in range(0, n) :
        d = j
        
        s = s + np.abs(a[i][j]) 
        s = s - np.abs(a[i][i])
            
        if (np.abs(a[i][i]) < s) :
            a[:, [d, i]] = a[:, [i,d]]
print(a)
                
                
                
 

[[13.  7.  3.]
 [ 3.  5.  1.]
 [-5.  3. 12.]]
