In [1]:
import nbconvert
nbconvert.NotebookExporter.output_mimetype = 'application/x-ipynb+json'
import numpy as np
from numpy import loadtxt


In [2]:
#Input
A = np.loadtxt('C:\Studies\Sem 4\PH206\Labs\Lab3\lab3matrix.txt',delimiter=',')
n = len(A)
U = np.zeros((n, n), dtype = np.double)
L = np.eye(n, dtype = np.double)

In [3]:
#Doolittle Decomposition
for i in range(n):
    for j in range(i+1):
        s1 = sum(U[k][i] * L[j][k] for k in range(j))
        U[j][i] = A[j][i] - s1
        
    for j in range(i, n):
        s2 = sum(U[k][i] * L[j][k] for k in range(j))
        L[j][i] = (A[j][i] - s2) / U[i][i]


In [4]:
#Solution and Checking
print(L)
print(U)
K = np.dot(L, U)
print(K)

[[1.         0.         0.         0.        ]
 [0.75       1.         0.         0.        ]
 [0.5        0.66666667 1.         0.        ]
 [0.25       0.33333333 0.5        1.        ]]
[[4.         3.         2.         1.        ]
 [0.         0.75       0.5        0.25      ]
 [0.         0.         0.66666667 0.33333333]
 [0.         0.         0.         0.5       ]]
[[4. 3. 2. 1.]
 [3. 3. 2. 1.]
 [2. 2. 2. 1.]
 [1. 1. 1. 1.]]


In [5]:
#Cholesky
C = np.zeros((n, n), dtype = np.double)
for i in range(n):
    for j in range(i+1):
        s3 = sum(C[i][k] * C[j][k] for k in range(j))
        if (i ==j):
            C[i][j] = np.sqrt(A[i][i] - s3) 
        else:
            C[i][j] = (1.0 / C[j][j] * (A[i][j] - s3))
            
print(C)

[[2.         0.         0.         0.        ]
 [1.5        0.8660254  0.         0.        ]
 [1.         0.57735027 0.81649658 0.        ]
 [0.5        0.28867513 0.40824829 0.70710678]]


In [6]:
#Checking

J = np.linalg.cholesky(A)
print(J)

[[2.         0.         0.         0.        ]
 [1.5        0.8660254  0.         0.        ]
 [1.         0.57735027 0.81649658 0.        ]
 [0.5        0.28867513 0.40824829 0.70710678]]


In [10]:
#Example problem

A = np.loadtxt('C:\Studies\Sem 4\PH206\Labs\Lab3\lab3matrix.txt',delimiter=',')
B = np.loadtxt('C:\Studies\Sem 4\PH206\Labs\Lab3\lab3matrix2.txt',delimiter=',')
n = len(A)
U = np.zeros((n, n), dtype = np.double)
L = np.eye(n, dtype = np.double)        

In [11]:
#Doolittle Method
for i in range(n):
    for j in range(i+1):
        s1 = sum(U[k][i] * L[j][k] for k in range(j))
        U[j][i] = A[j][i] - s1
        
    for j in range(i, n):
        s2 = sum(U[k][i] * L[j][k] for k in range(j))
        L[j][i] = (A[j][i] - s2) / U[i][i]
        
y = np.zeros(n)
x = np.zeros(n)

#forward substitution 
for i in range(n):
    t1 = B[i]
    for j in range(i):
        t1 = t1 - L[i][j] * y[j]
    y[i] = t1 / L[i][i]
    
#backward substitution 
for k in range(n-1, -1, -1):
    t2 = y[k]
    for l in range(k+1, n):
        t2 = t2 - U[k][l] * x[l]
    x[k] = t2 / U[k][k]
    
print(x)
print(y)
    
        
    


[  27.15 -117.85  107.1    38.6 ]
[  7.85       -25.1875      84.26666667  19.3       ]


In [12]:
#Cholesky method

C = np.zeros((n, n), dtype = np.double)
CT = np.transpose(C)
for i in range(n):
    for j in range(i+1):
        s3 = sum(C[i][k] * C[j][k] for k in range(j))
        if (i ==j):
            C[i][j] = np.sqrt(A[i][i] - s3) 
        else:
            C[i][j] = (1.0 / C[j][j] * (A[i][j] - s3))

y = np.zeros(n)
x = np.zeros(n)

#forward substitution 
for i in range(n):
    t1 = B[i]
    for j in range(i):
        t1 = t1 - C[i][j] * y[j]
    y[i] = t1 / C[i][i]
    
#backward substitution 
for k in range(n-1, -1, -1):
    t2 = y[k]
    for l in range(k+1, n):
        t2 = t2 - CT[k][l] * x[l]
    x[k] = t2 / CT[k][k]
    
print(x)
print(y)

[  27.15 -117.85  107.1    38.6 ]
[  3.925      -29.08401981 103.20516783  27.29432175]
