In [2]:

import numpy as np
from numpy import loadtxt
import sys

# Input
a = np.loadtxt('C:\Studies\Sem 4\PH206\Labs\Lab5\lab5matrix.txt',delimiter=',')
n = len(a)
x = np.ones((n))

# Reading tolerable error
tolerable_error = float(input('Enter tolerable error: '))

# Reading maximum number of steps
max_iteration = int(input('Enter maximum number of steps: '))
lambda_old = 1.0
condition =  True
step = 1
while condition:
    # Multiplying a and x
    x = np.matmul(a,x)
    
    # Finding new Eigen value and Eigen vector
    lambda_new = max(abs(x))
    
    x = x/lambda_new
    
    # Displaying Eigen value and Eigen Vector
    print('\nSTEP %d' %(step))
    print('----------')
    print('Eigen Value = %0.6f' %(lambda_new))
    print('Eigen Vector: ')
    for i in range(n):
        print('%0.3f\t' % (x[i]))
    
    # Checking maximum iteration
    step = step + 1
    if step > max_iteration:
        print('Not convergent in given maximum iteration!')
        break
    
    # Calculating error
    error = abs(lambda_new - lambda_old)
    print('error='+ str(error))
    lambda_old = lambda_new
    condition = error > tolerable_error

Enter tolerable error: 0.000001
Enter maximum number of steps: 100

STEP 1
----------
Eigen Value = 40.000000
Eigen Vector: 
0.000	
0.000	
-1.000	
errror=39.0

STEP 2
----------
Eigen Value = 50.000000
Eigen Vector: 
-0.400	
1.000	
0.200	
errror=10.0

STEP 3
----------
Eigen Value = 60.000000
Eigen Vector: 
0.433	
0.433	
-1.000	
errror=10.0

STEP 4
----------
Eigen Value = 71.666667
Eigen Vector: 
-0.400	
1.000	
-0.042	
errror=11.666666666666671

STEP 5
----------
Eigen Value = 57.581395
Eigen Vector: 
0.368	
0.662	
-1.000	
errror=14.085271317829466

STEP 6
----------
Eigen Value = 80.137318
Eigen Vector: 
-0.305	
1.000	
-0.196	
errror=22.5559229064132

STEP 7
----------
Eigen Value = 54.129624
Eigen Vector: 
0.281	
0.864	
-1.000	
errror=26.007694225414703

STEP 8
----------
Eigen Value = 87.369372
Eigen Vector: 
-0.227	
1.000	
-0.316	
errror=33.239747688163625

STEP 9
----------
Eigen Value = 53.516862
Eigen Vector: 
0.196	
1.000	
-0.960	
errror=33.852509715104986

STEP 10
----------


In [3]:
a = np.loadtxt('C:\Studies\Sem 4\PH206\Labs\Lab5\lab5matrix.txt',delimiter=',')
n = len(a)
x = np.ones((n))
b = np.linalg.inv(a)
# Reading tolerable error
tolerable_error = float(input('Enter tolerable error: '))

# Reading maximum number of steps
max_iteration = int(input('Enter maximum number of steps: '))
lambda_old = 1.0
condition =  True
step = 1
while condition:
    # Multiplying a and x
    x = np.matmul(b,x)
    
    # Finding new Eigen value and Eigen vector
    lambda_new = min(x)
    
    x = x/lambda_new
    
    # Displaying Eigen value and Eigen Vector
    print('\nSTEP %d' %(step))
    print('----------')
    print('Eigen Value = %0.6f' %(1 / lambda_new))
    print('Eigen Vector: ')
    for i in range(n):
        print('%0.3f\t' % (x[i]))
    
    # Checking maximum iteration
    step = step + 1
    if step > max_iteration:
        print('Not convergent in given maximum iteration!')
        break
    
    # Calculating error
    error = abs((1 / lambda_new) - (1 / lambda_old))
    print('errror='+ str(error))
    lambda_old = lambda_new
    condition = error > tolerable_error

Enter tolerable error: 0.000001
Enter maximum number of steps: 12

STEP 1
----------
Eigen Value = -10.196078
Eigen Vector: 
1.000	
0.451	
0.765	
errror=11.196078431372548

STEP 2
----------
Eigen Value = -12.093023
Eigen Vector: 
1.000	
0.451	
0.670	
errror=1.8969448244414036

STEP 3
----------
Eigen Value = -12.450025
Eigen Vector: 
1.000	
0.435	
0.660	
errror=0.3570013088456907

STEP 4
----------
Eigen Value = -12.531807
Eigen Vector: 
1.000	
0.434	
0.656	
errror=0.08178223522700812

STEP 5
----------
Eigen Value = -12.548327
Eigen Vector: 
1.000	
0.434	
0.656	
errror=0.016520253857061462

STEP 6
----------
Eigen Value = -12.552058
Eigen Vector: 
1.000	
0.434	
0.656	
errror=0.0037314329775863797

STEP 7
----------
Eigen Value = -12.552829
Eigen Vector: 
1.000	
0.433	
0.656	
errror=0.000770016867237544

STEP 8
----------
Eigen Value = -12.553000
Eigen Vector: 
1.000	
0.433	
0.656	
errror=0.00017121946706666336

STEP 9
----------
Eigen Value = -12.553036
Eigen Vector: 
1.000	
0.433	
0

In [4]:
# Problem 2

# Generating matrix

def matrix():
    n = 10
    x = 4*(np.identity(n))
    y = np.zeros((n, n))
    j = 1
    for i in range(0, n-1):
        y[i][j] = 2
        j += 1
    z = np.zeros((n, n))
    k = 2
    for i in range(0, n-2):
        z[i][k] = 1
        k += 1
        
    M = x + y + z + np.transpose(y) + np.transpose(z)
    return M

# Power method
M = matrix()
n = len(M)
x = np.ones((n))
print(M)
# Reading tolerable error
tolerable_error = float(input('Enter tolerable error: '))

# Reading maximum number of steps
max_iteration = int(input('Enter maximum number of steps: '))
lambda_old = 1.0
condition =  True
step = 1
while condition:
    # Multiplying a and x
    x = np.matmul(M,x)
    
    # Finding new Eigen value and Eigen vector
    lambda_new = max(abs(x))
    
    x = x/lambda_new
    
    # Displaying Eigen value and Eigen Vector
    print('\nSTEP %d' %(step))
    print('----------')
    print('Eigen Value = %0.6f' %(lambda_new))
    print('Eigen Vector: ')
    for i in range(n):
        print('%0.3f\t' % (x[i]))
    
    # Checking maximum iteration
    step = step + 1
    if step > max_iteration:
        print('Not convergent in given maximum iteration!')
        break
    
    # Calculating error
    error = abs(lambda_new - lambda_old)
    print('errror='+ str(error))
    lambda_old = lambda_new
    condition = error > tolerable_error
    


[[4. 2. 1. 0. 0. 0. 0. 0. 0. 0.]
 [2. 4. 2. 1. 0. 0. 0. 0. 0. 0.]
 [1. 2. 4. 2. 1. 0. 0. 0. 0. 0.]
 [0. 1. 2. 4. 2. 1. 0. 0. 0. 0.]
 [0. 0. 1. 2. 4. 2. 1. 0. 0. 0.]
 [0. 0. 0. 1. 2. 4. 2. 1. 0. 0.]
 [0. 0. 0. 0. 1. 2. 4. 2. 1. 0.]
 [0. 0. 0. 0. 0. 1. 2. 4. 2. 1.]
 [0. 0. 0. 0. 0. 0. 1. 2. 4. 2.]
 [0. 0. 0. 0. 0. 0. 0. 1. 2. 4.]]
Enter tolerable error: 0.000001
Enter maximum number of steps: 10

STEP 1
----------
Eigen Value = 10.000000
Eigen Vector: 
0.700	
0.900	
1.000	
1.000	
1.000	
1.000	
1.000	
1.000	
0.900	
0.700	
errror=9.0

STEP 2
----------
Eigen Value = 10.000000
Eigen Vector: 
0.560	
0.800	
0.950	
0.990	
1.000	
1.000	
0.990	
0.950	
0.800	
0.560	
errror=0.0


In [6]:
# Inverse Power Method
n = len(M)
x = np.ones((n))
N = np.linalg.inv(M)
# Reading tolerable error
tolerable_error = float(input('Enter tolerable error: '))
max_iteration = int(input('Enter maximum number of steps: '))

lambda_old = 1.0
condition =  True
step = 1
while condition:
    # Multiplying a and x
    x = np.matmul(N,x)
    
    # Finding new Eigen value and Eigen vector
    lambda_new = min(x)
    
    x = x/lambda_new
    
    # Displaying Eigen value and Eigen Vector
    print('\nSTEP %d' %(step))
    print('----------')
    print('Eigen Value = %0.6f' %(1 / lambda_new))
    print('Eigen Vector: ')
    for i in range(n):
        print('%0.3f\t' % (x[i]))
    
    # Checking maximum iteration
    step = step + 1
    if step > max_iteration:
        print('Not convergent in given maximum iteration!')
        break
    
    # Calculating error
    error = abs((1 / lambda_new) - (1 / lambda_old))
    print('errror='+ str(error))
    lambda_old = lambda_new
    condition = error > tolerable_error


Enter tolerable error: 0.000001
Enter maximum number of steps: 3321

STEP 1
----------
Eigen Value = 13.214286
Eigen Vector: 
2.464	
1.179	
1.000	
1.571	
1.250	
1.250	
1.571	
1.000	
1.179	
2.464	
errror=12.214285714285714

STEP 2
----------
Eigen Value = -7.645756
Eigen Vector: 
-5.406	
1.000	
0.782	
-3.764	
0.159	
0.159	
-3.764	
0.782	
1.000	
-5.406	
errror=20.860042171850296

STEP 3
----------
Eigen Value = -0.350967
Eigen Vector: 
0.858	
-0.574	
-0.385	
1.000	
-0.445	
-0.445	
1.000	
-0.385	
-0.574	
0.858	
errror=7.294788995647021

STEP 4
----------
Eigen Value = -2.147819
Eigen Vector: 
-1.128	
1.000	
0.672	
-1.853	
0.974	
0.974	
-1.853	
0.672	
1.000	
-1.128	
errror=1.7968515038440296

STEP 5
----------
Eigen Value = -0.633000
Eigen Vector: 
0.510	
-0.486	
-0.355	
1.000	
-0.544	
-0.544	
1.000	
-0.355	
-0.486	
0.510	
errror=1.5148190916023871

STEP 6
----------
Eigen Value = -2.171002
Eigen Vector: 
-0.850	
0.815	
0.661	
-1.827	
1.000	
1.000	
-1.827	
0.661	
0.815	
-0.850	
errror=1.53

-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966195594255912

STEP 158
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966195594255863

STEP 159
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.596619559425585

STEP 160
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966195594255796

STEP 161
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966195594255783

STEP 162
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966195594255725

STEP 163
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.39

Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.596619559423199

STEP 325
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.596619559423182

STEP 326
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966195594231212

STEP 327
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966195594231036

STEP 328
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966195594230406

STEP 329
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966195594230226

STEP 330
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	

Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966195593758967

STEP 525
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.59661955937557

STEP 526
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966195593744021

STEP 527
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966195593740657

STEP 528
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966195593728627

STEP 529
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966195593725163

STEP 530
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	

-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966195590737406

STEP 658
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966195590655574

STEP 659
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966195590632002

STEP 660
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.596619559054771

STEP 661
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966195590523435

STEP 662
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966195590436616

STEP 663
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.3

0.621	
-0.727	
errror=1.5966195483910517

STEP 891
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966195483188614

STEP 892
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966195480606782

STEP 893
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966195479863265

STEP 894
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.596619547720413

STEP 895
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966195476438356

STEP 896
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.59661954736

Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966194907053597

STEP 1015
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966194902557849

STEP 1016
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.596619488647912

STEP 1017
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966194881848774

STEP 1018
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966194865288657

STEP 1019
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966194860519682

STEP 1020
----------
Eigen Value = -2.244336
Eigen Vector: 
-0.727	
0.621	

Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966180723577315

STEP 1224
----------
Eigen Value = -2.244335
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966180377905153

STEP 1225
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5966180278358535

STEP 1226
----------
Eigen Value = -2.244335
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966179922337167

STEP 1227
----------
Eigen Value = -0.647717
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.596617981981019

STEP 1228
----------
Eigen Value = -2.244335
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5966179453129778

STEP 1229
----------
Eigen Value = -0.647717
Eigen

STEP 1424
----------
Eigen Value = -2.244314
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5965904875235029

STEP 1425
----------
Eigen Value = -0.647723
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5965902973314683

STEP 1426
----------
Eigen Value = -2.244313
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5965896171364817

STEP 1427
----------
Eigen Value = -0.647724
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5965894212502243

STEP 1428
----------
Eigen Value = -2.244312
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.596588720691083

STEP 1429
----------
Eigen Value = -0.647724
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5965885189401212

STEP 1430
----------
Eigen Va

STEP 1587
----------
Eigen Value = -0.647788
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5963003959050888

STEP 1588
----------
Eigen Value = -2.244081
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5962929779625623

STEP 1589
----------
Eigen Value = -0.647790
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5962908412690417

STEP 1590
----------
Eigen Value = -2.244074
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5962832012928572

STEP 1591
----------
Eigen Value = -0.647793
Eigen Vector: 
0.391	
-0.334	
-0.424	
1.000	
-0.537	
-0.537	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5962810006291481

STEP 1592
----------
Eigen Value = -2.244066
Eigen Vector: 
-0.727	
0.621	
0.790	
-1.861	
1.000	
1.000	
-1.861	
0.790	
0.621	
-0.727	
errror=1.5962731319750931

STEP 1593
----------
Eigen V

-0.727	
errror=1.591841206151223

STEP 1771
----------
Eigen Value = -0.648794
Eigen Vector: 
0.390	
-0.333	
-0.425	
1.000	
-0.536	
-0.538	
1.000	
-0.424	
-0.334	
0.391	
errror=1.5918099089633884

STEP 1772
----------
Eigen Value = -2.240492
Eigen Vector: 
-0.726	
0.619	
0.790	
-1.858	
0.996	
1.000	
-1.858	
0.787	
0.622	
-0.727	
errror=1.5916983542705363

STEP 1773
----------
Eigen Value = -0.648826
Eigen Vector: 
0.390	
-0.333	
-0.425	
1.000	
-0.536	
-0.538	
1.000	
-0.424	
-0.335	
0.391	
errror=1.591666120298858

STEP 1774
----------
Eigen Value = -2.240377
Eigen Vector: 
-0.726	
0.619	
0.790	
-1.858	
0.996	
1.000	
-1.858	
0.787	
0.622	
-0.727	
errror=1.5915512381749433

STEP 1775
----------
Eigen Value = -0.648859
Eigen Vector: 
0.390	
-0.333	
-0.425	
1.000	
-0.536	
-0.538	
1.000	
-0.424	
-0.335	
0.391	
errror=1.5915180393869472

STEP 1776
----------
Eigen Value = -2.240259
Eigen Vector: 
-0.726	
0.619	
0.790	
-1.858	
0.996	
1.000	
-1.858	
0.787	
0.622	
-0.727	
errror=1.5913997309650

errror=1.5518802793173592

STEP 1924
----------
Eigen Value = -2.208703
Eigen Vector: 
-0.710	
0.598	
0.788	
-1.828	
0.966	
1.000	
-1.832	
0.765	
0.623	
-0.720	
errror=1.550861563436086

STEP 1925
----------
Eigen Value = -0.658144
Eigen Vector: 
0.388	
-0.327	
-0.430	
0.998	
-0.527	
-0.546	
1.000	
-0.417	
-0.340	
0.393	
errror=1.5505588120511498

STEP 1926
----------
Eigen Value = -2.207654
Eigen Vector: 
-0.710	
0.598	
0.788	
-1.827	
0.965	
1.000	
-1.831	
0.764	
0.623	
-0.720	
errror=1.5495106495642335

STEP 1927
----------
Eigen Value = -0.658456
Eigen Vector: 
0.388	
-0.326	
-0.431	
0.998	
-0.527	
-0.546	
1.000	
-0.417	
-0.340	
0.393	
errror=1.5491988559644203

STEP 1928
----------
Eigen Value = -2.206576
Eigen Vector: 
-0.709	
0.597	
0.788	
-1.826	
0.964	
1.000	
-1.830	
0.763	
0.623	
-0.719	
errror=1.5481204275557392

STEP 1929
----------
Eigen Value = -0.658777
Eigen Vector: 
0.388	
-0.326	
-0.431	
0.997	
-0.527	
-0.547	
1.000	
-0.417	
-0.341	
0.393	
errror=1.5477993223557176

ST

0.666	
1.000	
-1.572	
0.544	
0.639	
-0.652	
errror=1.131441892958321

STEP 2091
----------
Eigen Value = -0.766863
Eigen Vector: 
0.356	
-0.251	
-0.492	
0.973	
-0.422	
-0.638	
1.000	
-0.345	
-0.408	
0.415	
errror=1.1280243478569

STEP 2092
----------
Eigen Value = -1.886214
Eigen Vector: 
-0.556	
0.391	
0.772	
-1.521	
0.658	
1.000	
-1.565	
0.538	
0.639	
-0.650	
errror=1.1193514817905732

STEP 2093
----------
Eigen Value = -0.770380
Eigen Vector: 
0.355	
-0.249	
-0.494	
0.972	
-0.419	
-0.641	
1.000	
-0.342	
-0.410	
0.416	
errror=1.1158344508494809

STEP 2094
----------
Eigen Value = -1.877371
Eigen Vector: 
-0.552	
0.385	
0.772	
-1.513	
0.649	
1.000	
-1.557	
0.531	
0.640	
-0.648	
errror=1.1069916176694696

STEP 2095
----------
Eigen Value = -0.773999
Eigen Vector: 
0.354	
-0.246	
-0.497	
0.971	
-0.415	
-0.644	
1.000	
-0.340	
-0.412	
0.416	
errror=1.1033722908591366

STEP 2096
----------
Eigen Value = -1.868357
Eigen Vector: 
-0.548	
0.379	
0.771	
-1.504	
0.641	
1.000	
-1.550	
0.525	
0.6

-0.386	
errror=1.4481877324839791

STEP 2275
----------
Eigen Value = -2.155621
Eigen Vector: 
-0.049	
0.715	
-1.285	
0.655	
0.919	
-1.808	
1.000	
0.583	
-1.267	
0.696	
errror=1.4846333761339032

STEP 2276
----------
Eigen Value = -0.659536
Eigen Vector: 
0.030	
-0.399	
0.711	
-0.357	
-0.514	
1.000	
-0.548	
-0.327	
0.701	
-0.384	
errror=1.496085158578115

STEP 2277
----------
Eigen Value = -2.192778
Eigen Vector: 
-0.060	
0.741	
-1.307	
0.646	
0.955	
-1.839	
1.000	
0.608	
-1.290	
0.703	
errror=1.5332413665795541

STEP 2278
----------
Eigen Value = -0.648257
Eigen Vector: 
0.035	
-0.406	
0.710	
-0.346	
-0.525	
1.000	
-0.539	
-0.335	
0.702	
-0.381	
errror=1.544520899071403

STEP 2279
----------
Eigen Value = -2.230649
Eigen Vector: 
-0.071	
0.767	
-1.328	
0.637	
0.991	
-1.871	
1.000	
0.633	
-1.313	
0.711	
errror=1.582392014285797

STEP 2280
----------
Eigen Value = -0.637150
Eigen Vector: 
0.041	
-0.413	
0.710	
-0.335	
-0.535	
1.000	
-0.530	
-0.342	
0.702	
-0.379	
errror=1.59349835721174

0.100	
-0.973	
1.000	
-0.150	
-0.665	
0.725	
-0.279	
errror=0.06598059166694958

STEP 2491
----------
Eigen Value = -1.220735
Eigen Vector: 
-0.267	
0.728	
-0.705	
-0.103	
1.000	
-1.027	
0.154	
0.684	
-0.745	
0.287	
errror=0.06498793524421642

STEP 2492
----------
Eigen Value = -1.156673
Eigen Vector: 
0.260	
-0.709	
0.687	
0.101	
-0.974	
1.000	
-0.149	
-0.666	
0.725	
-0.279	
errror=0.06406152177199886

STEP 2493
----------
Eigen Value = -1.219772
Eigen Vector: 
-0.267	
0.728	
-0.705	
-0.104	
1.000	
-1.027	
0.153	
0.684	
-0.745	
0.286	
errror=0.0630984974475326

STEP 2494
----------
Eigen Value = -1.157573
Eigen Vector: 
0.260	
-0.710	
0.687	
0.101	
-0.975	
1.000	
-0.149	
-0.667	
0.725	
-0.279	
errror=0.06219831819654709

STEP 2495
----------
Eigen Value = -1.218837
Eigen Vector: 
-0.267	
0.728	
-0.704	
-0.104	
1.000	
-1.026	
0.152	
0.684	
-0.744	
0.286	
errror=0.061264019233270295

STEP 2496
----------
Eigen Value = -1.158448
Eigen Vector: 
0.261	
-0.710	
0.687	
0.102	
-0.975	
1.000	


Eigen Value = -1.190830
Eigen Vector: 
-0.273	
0.727	
-0.687	
-0.125	
1.000	
-1.002	
0.129	
0.685	
-0.728	
0.274	
errror=0.005616485135157667

STEP 2658
----------
Eigen Value = -1.185296
Eigen Vector: 
0.272	
-0.725	
0.685	
0.124	
-0.998	
1.000	
-0.129	
-0.684	
0.727	
-0.274	
errror=0.005534440011209618

STEP 2659
----------
Eigen Value = -1.190749
Eigen Vector: 
-0.273	
0.727	
-0.687	
-0.125	
1.000	
-1.002	
0.129	
0.685	
-0.728	
0.274	
errror=0.005453221442025757

STEP 2660
----------
Eigen Value = -1.185375
Eigen Vector: 
0.272	
-0.725	
0.685	
0.124	
-0.998	
1.000	
-0.129	
-0.684	
0.727	
-0.274	
errror=0.005373555905753724

STEP 2661
----------
Eigen Value = -1.190670
Eigen Vector: 
-0.273	
0.727	
-0.687	
-0.125	
1.000	
-1.002	
0.129	
0.685	
-0.728	
0.274	
errror=0.005294703552074953

STEP 2662
----------
Eigen Value = -1.185453
Eigen Vector: 
0.272	
-0.725	
0.685	
0.125	
-0.998	
1.000	
-0.129	
-0.684	
0.727	
-0.274	
errror=0.0052173487392548346

STEP 2663
----------
Eigen Value = -

----------
Eigen Value = -1.188185
Eigen Vector: 
-0.273	
0.727	
-0.685	
-0.127	
1.000	
-1.000	
0.127	
0.685	
-0.727	
0.273	
errror=0.0002939711472242923

STEP 2858
----------
Eigen Value = -1.187895
Eigen Vector: 
0.273	
-0.727	
0.685	
0.127	
-1.000	
1.000	
-0.127	
-0.685	
0.727	
-0.273	
errror=0.0002896674231653851

STEP 2859
----------
Eigen Value = -1.188181
Eigen Vector: 
-0.273	
0.727	
-0.685	
-0.127	
1.000	
-1.000	
0.127	
0.685	
-0.727	
0.273	
errror=0.00028542568647527133

STEP 2860
----------
Eigen Value = -1.187900
Eigen Vector: 
0.273	
-0.727	
0.685	
0.127	
-1.000	
1.000	
-0.127	
-0.685	
0.727	
-0.273	
errror=0.000281247052869249

STEP 2861
----------
Eigen Value = -1.188177
Eigen Vector: 
-0.273	
0.727	
-0.685	
-0.127	
1.000	
-1.000	
0.127	
0.685	
-0.727	
0.273	
errror=0.00027712863390805254

STEP 2862
----------
Eigen Value = -1.187904
Eigen Vector: 
0.273	
-0.727	
0.685	
0.127	
-1.000	
1.000	
-0.127	
-0.685	
0.727	
-0.273	
errror=0.00027307145534005706

STEP 2863
--------

0.685	
0.127	
-1.000	
1.000	
-0.127	
-0.685	
0.727	
-0.273	
errror=9.456843860444764e-06

STEP 3091
----------
Eigen Value = -1.188044
Eigen Vector: 
-0.273	
0.727	
-0.685	
-0.127	
1.000	
-1.000	
0.127	
0.685	
-0.727	
0.273	
errror=9.318378808353955e-06

STEP 3092
----------
Eigen Value = -1.188035
Eigen Vector: 
0.273	
-0.727	
0.685	
0.127	
-1.000	
1.000	
-0.127	
-0.685	
0.727	
-0.273	
errror=9.181942185687575e-06

STEP 3093
----------
Eigen Value = -1.188044
Eigen Vector: 
-0.273	
0.727	
-0.685	
-0.127	
1.000	
-1.000	
0.127	
0.685	
-0.727	
0.273	
errror=9.04750219921091e-06

STEP 3094
----------
Eigen Value = -1.188035
Eigen Vector: 
0.273	
-0.727	
0.685	
0.127	
-1.000	
1.000	
-0.127	
-0.685	
0.727	
-0.273	
errror=8.915031647793725e-06

STEP 3095
----------
Eigen Value = -1.188043
Eigen Vector: 
-0.273	
0.727	
-0.685	
-0.127	
1.000	
-1.000	
0.127	
0.685	
-0.727	
0.273	
errror=8.784499721414818e-06

STEP 3096
----------
Eigen Value = -1.188035
Eigen Vector: 
0.273	
-0.727	
0.685	
0.12